#!/bin/bash
echo "=== BOOK TABLE COUNT ==="
sqlite3 /opt/kizana/data/kizana_all_books.sqlite "SELECT count(name) FROM sqlite_master WHERE type='table' AND name GLOB 'b[0-9]*';"
echo "=== TOC TABLE COUNT ==="
sqlite3 /opt/kizana/data/kizana_all_books.sqlite "SELECT count(name) FROM sqlite_master WHERE type='table' AND name GLOB 't[0-9]*';"
echo "=== HIGHEST BOOK ==="
sqlite3 /opt/kizana/data/kizana_all_books.sqlite "SELECT name FROM sqlite_master WHERE type='table' AND name GLOB 'b[0-9]*' ORDER BY CAST(SUBSTR(name,2) AS INTEGER) DESC LIMIT 3;"
echo "=== OTHER TABLES ==="
sqlite3 /opt/kizana/data/kizana_all_books.sqlite "SELECT name FROM sqlite_master WHERE type='table' AND name NOT GLOB 'b[0-9]*' AND name NOT GLOB 't[0-9]*';"
echo "=== SAMPLE BOOK b1 ROWS ==="
sqlite3 /opt/kizana/data/kizana_all_books.sqlite "SELECT count(id) FROM b1;"
echo "=== SAMPLE TOC t1 ROWS ==="
sqlite3 /opt/kizana/data/kizana_all_books.sqlite "SELECT count(id) FROM t1;"
echo "=== DEPLOY start.sh ==="
cat /opt/kizana/deploy/start.sh
echo "=== PRODUK CATEGORIES ==="
sqlite3 /opt/kizana/data/produk_hukum.sqlite "SELECT name, doc_count FROM categories ORDER BY doc_count DESC;"
echo "=== TANTIVY TOTAL DOCS ==="
echo "Sum from meta.json segments:"
cat /opt/kizana/tantivy_index/meta.json | python3 -c "import json,sys; d=json.load(sys.stdin); print(sum(s['max_doc'] for s in d['segments']))"
